---
- import_tasks: ../../common_actions/required_vars.yml

- name: Ensure nextcloud dependencies are present
  apt:
    name: "{{ item }}"
    state: present
  when: app_present
  with_items: "{{ deps.deps }}"

- name: Ensure ansible dependencies for mysql are present
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ deps.ansible_deps }}"
