---
- import_tasks: ../../common_actions/required_vars.yml

- name: Ensure nextcloud dependencies are present
  apt:
    name: "{{ deps.deps }}"
    state: present
  tags: install_app

- name: Ensure ansible dependencies for mysql are present
  apt:
    name: "{{ deps.ansible_deps }}"
    state: present
  tags: install_app
