---
- import_tasks: ../../common_actions/required_vars.yml

- name: "Copy php-fpm conf"
  template:
    src: "{{ php_fpm.pool_conf }}"
    dest: "/etc/php/7.0/fpm/pool.d/{{ app.instance }}.conf"
    owner: root
    mode: 0644
  notify: restart php-fpm
  when: app_present

- name: "Copy php-fpm ini conf"
  template:
    src: "{{ php_fpm.ini_conf }}"
    dest: /etc/php/7.0/fpm/conf.d/20-{{ app.instance }}.ini
    owner: root
    mode: 0644
  notify: restart php-fpm
  when: app_present

- name: "php-fpm conf removal"
  file:
    path: "/etc/php/7.0/fpm/pool.d/{{ app.instance }}.conf"
    state: absent
  notify: restart php-fpm
  when: app_absent

- name: "php-fpm ini conf removal"
  file:
    path: /etc/php/7.0/fpm/conf.d/20-{{ app.instance }}.ini
    state: absent
  notify: restart php-fpm
  when: app_absent
