---
- name: fetch main domain file
  slurp:
    src: /etc/yunohost/current_host
  register: current_host
  tags: install_app, remove_app

- name: fetch ssowat conf
  slurp:
    src: /etc/ssowat/conf.json
  register: ssowat_conf_fetch
  tags: install_app, remove_app



- name: register install state variables
  set_fact:
    creation: create
    dir_state: directory
  changed_when: False
  # when: app.state == 'present'
  tags: install_app



- name: register remove state variables
  set_fact:
    creation: remove
    dir_state: absent
  changed_when: False
  # when: app.state == 'absent'
  tags: remove_app


- name: register webroot & datadir & main_domain ansible variables
  set_fact:
    datadir: /home/yunohost.app/{{ app.instance }}/data
    webroot: /var/www/{{ app.instance }}
    main_domain: "{{ current_host['content'] | b64decode }}"
  changed_when: False
  tags: install_app, remove_app
