#!/usr/bin/env ansible-playbook

# - import_playbook: known_host_clean.ansible.yml

- hosts: localhost
  roles:
    - role: nextcloud_ynh
      vars:
        app:
          instance: nextcloud
          user: nextcloud
          role: nextcloud_ynh
          name: nextcloud
          state: present
          domain: devpl.uk
          admin: elie
          webpath: /nextcloud
          use_user_home_dirs: True
          version: 13.0.6


